/* Catálogo de faltas y sanciones — Reglamento Interno de Trabajo COMBUSES S.A.
   ARTÍCULO 108. Escala de faltas y sanciones (122 faltas).
   s = [PRIMERA VEZ, SEGUNDA VEZ, TERCERA VEZ, CUARTA VEZ]
   Códigos: LA=Llamado de atención escrito · S#=Suspensión de # días · FG=Falta grave y justa causa para terminar el contrato */
(function () {
  const LA = 'Llamado de atención por escrito';
  const S = d => `Suspensión de ${d} días`;
  const FG = 'Falta grave y justa causa para dar por terminado el contrato';
  const f = (n, d, s) => ({ n, d, s });
  window.CATALOGO_FALTAS = [
    f(1,'Retardo injustificado en el inicio de labores',[LA,S(2),S(8),FG]),
    f(2,'Incumplir con el horario laboral',[LA,S(2),S(8),FG]),
    f(3,'Realizar caídas o adelantos a los puntos de control',[LA,S(2),S(8),FG]),
    f(4,'Inasistencia total o parcial a una jornada de trabajo sin justa causa',[S(5),S(15),S(30),FG]),
    f(5,'Ausentarse total o parcialmente del puesto de trabajo sin la correspondiente autorización, o abandonar la ruta sin justificación',[S(8),S(15),FG,'']),
    f(6,'Conducir el vehículo superando los límites de velocidad permitida o realizar maniobras peligrosas',[S(8),S(15),FG,'']),
    f(7,'Incumplir sin justa causa las órdenes de los gestores de movilidad o líderes de áreas de operaciones y gestión y control de flota',[S(8),FG,'','']),
    f(8,'Incumplir sin justa causa las órdenes de los jefes inmediatos',[S(8),FG,'','']),
    f(9,'Descuidar el orden e higiene de su aspecto personal, portar inadecuadamente o no usar el uniforme de trabajo entregado como dotación, carnet o implementos de trabajo',[LA,S(8),FG,'']),
    f(10,'Inasistencia sin justificación a reuniones, capacitaciones y demás encuentros programados por la empresa',[LA,S(2),S(5),FG]),
    f(11,'No portar la orden de despacho',[LA,S(2),S(5),FG]),
    f(12,'No reportar las novedades del día de forma oportuna',[LA,S(2),S(5),FG]),
    f(13,'No realizar la revisión diaria de los documentos del vehículo y preoperacional',[LA,S(2),S(5),FG]),
    f(14,'No despachar los vehículos en la plataforma de Sonar o cualquier plataforma(s) dispuesta por la empresa para el manejo operacional',[LA,S(2),S(5),FG]),
    f(15,'Prestar mala atención a los usuarios, no hacer debida gestión de tiquetes y equipaje',[S(2),S(5),FG,'']),
    f(16,'Ser déspota, no ser oportuno, ser grosero, vulgar o negarse a prestar debidamente el servicio a clientes, usuarios y compañeros de trabajo',[S(8),FG,'','']),
    f(17,'Informar de forma inexacta los horarios de salida de los vehículos',[S(2),S(5),FG,'']),
    f(18,'No llevar el control de pasajeros de cada vehículo, permitir el sobrecupo y otros controles documentales, de elementos y presentación de vehículo',[S(2),S(5),FG,'']),
    f(19,'No informar el estado del vehículo según el chequeo preoperacional',[S(2),S(5),FG,'']),
    f(20,'No diligenciar en debida forma el chequeo preoperacional con firma del conductor y del gestor',[S(2),S(5),FG,'']),
    f(21,'No reportar el ausentismo o cualquier novedad de los conductores',[LA,S(2),S(5),FG]),
    f(22,'Tener el puesto de despacho en malas condiciones de higiene o desordenado',[LA,S(2),S(5),FG]),
    f(23,'Hacer despachos a carros que sean manejados por personas no autorizadas o no vinculadas con la empresa',[FG,'','','']),
    f(24,'Adulterar, manipular las planillas de despacho, aplicativo o cualquier mecanismo en cuanto al control y número de pasajeros',[S(5),FG,'','']),
    f(25,'Realizar actividades no propias de su cargo como gestor de movilidad, de servicio o el cargo para el cual ha sido contratado',[S(2),S(5),FG,'']),
    f(26,'Realizar o participar en juegos de azar, rifas, loterías, captación de dinero en cualquier modalidad, venta de mercancía',[LA,S(2),S(5),FG]),
    f(27,'Disponer de los elementos de trabajo por fuera de la jornada laboral',[LA,S(2),S(5),FG]),
    f(28,'Hacerse cargo de maletas o paquetes no aforados dentro de las oficinas de despacho',[LA,S(2),S(5),FG]),
    f(29,'No hacer entrega de elementos dejados en los vehículos por los usuarios',[S(8),FG,'','']),
    f(30,'Realizar con los conductores o gestores de movilidad juegos de manos, tener exceso de confianza, ponerse seudónimos o calificativos',[LA,S(2),S(5),FG]),
    f(31,'No informar o realizar el mantenimiento predictivo, preventivo y correctivo al vehículo',[LA,LA,S(5),FG]),
    f(32,'No realizar la revisión del estado del vehículo incluyendo extintores y botiquín de primeros auxilios',[LA,S(2),S(5),FG]),
    f(33,'No ingresar los itinerarios a la plataforma de Sonar',[LA,S(2),S(5),FG]),
    f(34,'Conducir el vehículo sin los permisos y documentos legales vigentes tales como tecnomecánica, pólizas de seguro, póliza de responsabilidad civil, licencia de conducción, tarjeta de despacho y carnet',[S(5),FG,'','']),
    f(35,'Cambiar turnos de trabajo sin autorización previa de su jefe inmediato',[S(2),S(5),FG,'']),
    f(36,'Retardar más de 24 horas la presentación de las liquidaciones y los respectivos reembolsos de las sumas de dinero que haya recibido',[S(5),FG,'','']),
    f(37,'No entregar o dar destinación diferente a los dineros recibidos',[FG,'','','']),
    f(38,'Incurrir en acto de violencia, injuria, malos tratos o grave indisciplina en sus labores, en contra de su empleador, los compañeros de trabajo, contratistas, usuarios o autoridades de tránsito',[FG,'','','']),
    f(39,'No presentar oportunamente las incapacidades médicas',[S(5),FG,'','']),
    f(40,'Utilizar más del tiempo asignado para citas médicas, reuniones y/o cualquier otra actividad; asimismo, utilizar los permisos o licencias en actividades distintas a las señaladas',[S(2),S(5),FG,'']),
    f(41,'Conducir hablando por celular',[S(8),FG,'','']),
    f(42,'Conducir sin hacer uso del cinturón de seguridad',[S(8),FG,'','']),
    f(43,'Realizar conductas de guerreo con otros vehículos',[FG,'','','']),
    f(44,'No realizar la inspección diaria del vehículo de los sistemas de dirección, frenos, luces, estado de llantas, combustible entre otros',[LA,S(2),S(5),FG]),
    f(45,'No llevar el vehículo al taller para su mantenimiento o reparación',[S(2),S(5),FG,'']),
    f(46,'No informar a la empresa las fallas mecánicas o técnicas del vehículo',[S(5),FG,'','']),
    f(47,'Cobrar dineros adicionales a la tarifa legal establecida',[FG,'','','']),
    f(48,'Incentivar o no hacer uso debido del validador de la Cívica',[S(5),FG,'','']),
    f(49,'No realizar el pago de las infracciones de tránsito',[LA,S(2),S(5),FG]),
    f(50,'Incumplir con las normas, procedimientos y estándares de higiene y seguridad en el trabajo',[FG,'','','']),
    f(51,'Incumplir con las normas establecidas del manual de funciones',[S(2),S(5),FG,'']),
    f(52,'Incumplir con las normas de tránsito y seguridad vial',[FG,'','','']),
    f(53,'Presentarse a laborar o conducir en estado de embriaguez o bajo la influencia de narcóticos o drogas enervantes',[FG,'','','']),
    f(54,'Consumir alcohol o sustancias alucinógenas en horario laboral',[FG,'','','']),
    f(55,'Manipular las cámaras de seguridad del vehículo',[FG,'','','']),
    f(56,'Manipular, bloquear o alterar los sensores de seguridad',[FG,'','','']),
    f(57,'Manipular, bloquear o alterar los equipos registradores',[FG,'','','']),
    f(58,'Permitir el ingreso de pasajeros por la puerta trasera del vehículo',[FG,'','','']),
    f(59,'Entregar el vehículo o permitir que este sea conducido por personal no vinculado a la compañía',[FG,'','','']),
    f(60,'Dejar el vehículo estacionado o abandonado en lugares no dispuestos por la empresa o el propietario',[FG,'','','']),
    f(61,'Incumplir las normas de tránsito diferentes a las expresamente señaladas como faltas',[S(2),S(5),FG,'']),
    f(62,'Transitar con las puertas del vehículo abiertas',[FG,'','','']),
    f(63,'Retardar injustificadamente el tiempo habitual de cada trayecto',[S(2),S(5),FG,'']),
    f(64,'No utilizar o usar inadecuadamente los implementos de seguridad y dotación estipulados para cada oficio y riesgo',[S(2),S(5),FG,'']),
    f(65,'No informar a la empresa la ocurrencia de un siniestro',[S(5),FG,'','']),
    f(66,'No informar las citaciones administrativas o judiciales que se realicen con relación al vehículo asignado',[S(5),FG,'','']),
    f(67,'No asistir a las citaciones judiciales o administrativas que se realicen con base a siniestros que se presenten',[S(5),FG,'','']),
    f(68,'Hacer arreglos, dar, ofrecer o recibir dádivas o incentivos a compañeros de trabajo, superiores, autoridades de tránsito o terceros con el fin de obtener cualquier beneficio',[FG,'','','']),
    f(69,'No respetar los turnos de los demás conductores',[S(2),S(5),FG,'']),
    f(70,'Ejecutar cualquier acto que ponga en peligro su seguridad, la de los compañeros, superiores, pasajeros, equipos o elementos de trabajo',[S(2),S(5),FG,'']),
    f(71,'Toda conducta que, en los términos del artículo 2 de la Ley 1010 de 2006, encuadre como una modalidad de acoso laboral',[S(5),FG,'','']),
    f(72,'Presentar al empleador certificados o documentos falsos o con información inexacta para obtener provecho',[FG,'','','']),
    f(73,'Negarse sin justa causa a practicarse los exámenes periódicos de salud programados para la seguridad y salud en el trabajo',[FG,'','','']),
    f(74,'Hacer trabajos distintos a su oficio dentro de la empresa, sin la debida autorización, incluye utilización del horario laboral para realizar trabajo de estudio u otros',[LA,S(2),S(5),FG]),
    f(75,'Encargar del trabajo propio a otro trabajador o desempeñar un oficio distinto del asignado sin autorización del superior, salvo imprescindibles necesidades del trabajo',[S(2),S(5),FG,'']),
    f(76,'Perder tiempo, obstaculizar el trabajo de los otros, teniendo una labor asignada',[LA,S(2),S(5),FG]),
    f(77,'Ingresar o retirar herramientas de trabajo o materiales de la empresa sin autorización',[S(2),S(5),FG,'']),
    f(78,'Encubrir las faltas cometidas por sus compañeros de trabajo, o dar informes que no correspondan a la realidad para los mismos efectos',[FG,'','','']),
    f(79,'Fumar en cualquier sitio de las instalaciones de la empresa, en horas de trabajo, o en los puestos de trabajo',[LA,S(2),S(5),FG]),
    f(80,'Mantener conversación continua con compañeros que realicen un mismo proceso en áreas que ocasione pérdida de concentración incurriendo en errores o suspensión del proceso',[LA,S(2),S(5),FG]),
    f(81,'Hacer uso indebido del servicio de cafetín, demorarse más del tiempo reglamentario en tomar los alimentos, sin causa justificada y/o estar en él horas diferentes a las establecidas',[LA,S(2),S(5),FG]),
    f(82,'Hacer mal uso del permiso concedido o no regresar a la empresa después de haber utilizado el permiso y no haberse terminado el turno',[S(2),S(5),S(10),FG]),
    f(83,'Conservar armas de cualquier clase en el sitio de trabajo',[FG,'','','']),
    f(84,'Disminuir intencionalmente el ritmo de ejecución de trabajo, colaborar en disturbios que perjudiquen el funcionamiento de COMBUSES S.A.',[FG,'','','']),
    f(85,'Dormir en el lugar de trabajo',[FG,'','','']),
    f(86,'Incitar al personal de trabajadores para que desconozcan las órdenes impartidas por sus superiores o jefes inmediatos',[FG,'','','']),
    f(87,'Realizar cualquier clase o tipo de reuniones no autorizadas dentro de las instalaciones de COMBUSES S.A.',[S(5),S(10),FG,'']),
    f(88,'Dar un uso indebido a los computadores o internet, utilizándolo para chatear, visitar páginas o material indeseados; instalar o desinstalar software en los computadores de la empresa',[S(5),S(10),FG,'']),
    f(89,'Hacer afirmaciones falsas o maliciosas de COMBUSES S.A. a sus trabajadores, proveedores o propietarios',[S(5),S(10),FG,'']),
    f(90,'No comunicar oportunamente al jefe inmediato sobre situación o hechos que puedan poner en riesgo a COMBUSES S.A. y sus empleados',[S(8),FG,'','']),
    f(91,'Engañar a COMBUSES S.A. en cuanto al uso inadecuado de anticipo de cesantías en finalidades diferentes a las establecidas por la ley, o presentar documentos ficticios o que adolezcan de veracidad',[S(8),FG,'','']),
    f(92,'Desatender las obligaciones del puesto de trabajo por atender de manera constante llamadas en el teléfono personal (celular) o estar chateando',[S(2),S(5),S(10),FG]),
    f(93,'Revelar información calificada como confidencial',[FG,'','','']),
    f(94,'Realizar auto préstamos de dinero',[FG,'','','']),
    f(95,'Utilizar el nombre de COMBUSES S.A. en objetivos diferentes al de la labor desempeñada, en beneficio propio o de un tercero',[FG,'','','']),
    f(96,'Hacerse anotar tiempo no trabajado como horas extras o trabajo suplementario',[FG,'','','']),
    f(97,'Dejar vencer plazos de cobros o reclamaciones ante personas naturales, jurídicas, entes administrativos, estatales y judiciales',[FG,'','','']),
    f(98,'Alterar, modificar, aumentar o disminuir los rubros contenidos en la nómina',[FG,'','','']),
    f(99,'Alterar la contabilidad, arqueos de caja, balances, facturas, recibos, pagarés y en general documentos contables',[FG,'','','']),
    f(100,'Omitir o consignar datos inexactos en los informes, cuadros, relaciones, balances o asientos que se presenten o requieran los superiores a fin de obtener decisiones o aprobaciones',[FG,'','','']),
    f(101,'Cometer errores en la elaboración de facturas, recibos o pagos, causando perjuicio económico a la empresa',[FG,'','','']),
    f(102,'No supervisar ni controlar las acciones derivadas de las labores propias de cada área que estén a su cargo',[FG,'','','']),
    f(103,'Ocultar faltas cometidas contra la empresa por algún trabajador',[FG,'','','']),
    f(104,'No informar oportunamente sobre posibles errores en la liquidación de algún pago',[LA,S(2),S(5),FG]),
    f(105,'Ingresar memorias USB o cualquier dispositivo con el fin de compartir o grabar información',[LA,S(2),S(5),FG]),
    f(106,'Violar el compromiso de exclusividad de servicios pactado en el contrato de trabajo, prestando servicios profesionales a terceros',[FG,'','','']),
    f(107,'El incumplimiento de memorandos, directrices, circulares de carácter informativo',[FG,'','','']),
    f(108,'Incumplir con el perfil de cargos y funciones, no realizar las funciones asignadas por su jefe o superior o cualquier representante del empleador en los términos estipulados y tiempos asignados',[FG,'','','']),
    f(109,'Incumplir las políticas definidas por la empresa en el manual de políticas y procedimientos de la compañía',[FG,'','','']),
    f(110,'Destruir las instalaciones de la compañía y/o dejar perder las herramientas de trabajo, los elementos de protección personal y pertenencias de la compañía o de los compañeros, de manera intencional o por desatención',[FG,'','','']),
    f(111,'Realizar actos considerados inmorales, inaceptables o delictivos dentro de las instalaciones de la compañía o con uso del uniforme de la compañía',[FG,'','','']),
    f(112,'Dejar de elaborar cualquier informe de trabajo que se le solicite o los propios de su cargo, no dar informes o darlos inexactos',[S(2),S(5),FG,'']),
    f(113,'Todo acto de deslealtad con el empleador, los propietarios de la sociedad, directivos o compañeros de trabajo',[FG,'','','']),
    f(114,'Fijar o remover material de las carteleras sin la autorización de la persona encargada o por lo menos del superior inmediato',[LA,S(2),S(5),FG]),
    f(115,'Falsificar documentación para provecho propio o de un tercero',[FG,'','','']),
    f(116,'No tener el control de su personal en cuanto a los turnos que deben cumplir, el trabajo que deben realizar y las condiciones de calidad y cantidad',[LA,S(5),S(10),FG]),
    f(117,'Dar a conocer a personas no autorizadas la clave personal de acceso a los sistemas de cómputo sin autorización',[S(5),FG,'','']),
    f(118,'No guardar riguroso cuidado y diligencia para hacer cumplir a su personal las normas de seguridad y salud en el trabajo',[S(5),S(10),FG,'']),
    f(119,'No realizar el registro biométrico o hacerlo en forma indebida',[S(2),S(5),S(10),FG]),
    f(120,'Violación por parte del trabajador de las obligaciones contractuales o reglamentarias, cuando causen un perjuicio de importancia a la empresa',[FG,'','','']),
    f(121,'Incumplir con las responsabilidades inherentes a su cargo',[FG,'','','']),
    f(122,'Toda conducta de acoso laboral sexual',[FG,'','','']),
  ];
})();
